### ISSUE TITLE
OnDemand wipes any module that user loads in ~/.bashrc - is that needed?

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4-ondemand-interactive-apps#12]
# Issue

When running the RStudio Server or Jupyter Notebook via OnDemand, all users runs in a clean slate, i.e. they run in an environment where `module purge` has been applied regardless of their personal `~/.bashrc` settings.

The problem with this is that the user cannot load modules, or apply other customizations to the environment, after RStudio or Jupyter is already running.  At least they cannot do it without major efforts (e.g. https://github.com/HenrikBengtsson/LinuxEnvironmentModules/issues/3).

# Proposal

* [x] Investigate if we can drop `module purge` from [`startup.sh.erb`](https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/blob/0a19803a13d89fb0247261b33fb3df8b86724ced/RStudio/template/script.sh.erb#L5)?

* [x] Set environment `ONDEMAND_APP=RStudioServer` in [`before.sh.erb`](https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/blob/main/RStudio/template/before.sh.erb), so that it's available to user's `~/.bashrc`, which is called by `startup.sh.erb`.  This allows the user to configure their environment conditionally on OnDemand running and what app.

```sh
$ cat ~/.bashrc
...
## Load different modules depending on which OnDemand app is running
case "${ONDEMAND_APP}" in
  RStudioServer)
    module load CBI cmake gdal geos gsl hdf5 jags proj
    ;;
  JupyterNotebook)
    conda active something-something
    ;;
esac
```

**Comment by hgputnam** [comment]
We can drop the module purge if you want, that is a recommendation not a requirement. Your approach with .bashrc ought to work. The other option would be to package modules like that into different variants of OnDemand apps.

**Comment by hgputnam** [comment]
Let me give it a try, I will copy the existing one to a new folder in this repo and work on it there.

**Comment by hgputnam** [comment]
I made a branch called development (I have no idea what I am doing). I see @HenrikBengtsson had a branch called 'devleopment' as well. I hope this won't cause problems...

**Comment by HenrikBengtsson** [comment]
> I made a branch called development (I have no idea what I am doing).

It's there. Compaing it to the main branch, there's just one teeny difference <https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/compare/development>.

> I see @HenrikBengtsson had a branch called 'devleopment' as well. I hope this won't cause problems...

Nope, I don't have a `development` branch in this repo, cf. https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/branches.  If I had one, you would not have been able to push your `development` branch.  (You might have seen the `HenrikBengtsson-patch-1` branch, which will disappear as soon as pull requestion #15 has been merged).

**Comment by HenrikBengtsson** [comment]
> We can drop the module purge if you want, that is a recommendation not a requirement.

Yes, I think we should do that.

**Comment by HenrikBengtsson** [comment]
@hgputnam , if you could drop the `module purge` line, that would be a great step forward here.

**Comment by hgputnam** [comment]
Sorry, meant to that a while ago. It has been dropped, deployed, and the app re-tested.

**Comment by hgputnam** [comment]
Ditto for new variable `ONDEMAND_APP=RStudioServer`

**Comment by HenrikBengtsson** [comment]
I've verified that `ONDEMAND_APP=RStudioServer` is set in the RStudio Server.

**Comment by HenrikBengtsson** [comment]
I can confirm that `module purge` is removed from `script.sh`:

```sh
$ cat ~/ondemand/data/sys/dashboard/batch_connect/sys/RStudio/output/36042511-00e3-4730-9c47-e672abb30be7/script.sh 
#!/usr/bin/env bash

# Load CBI rsc module

module load CBI rstudio-server-controller

# Star the rsc script whcih will launch rstudio-server.
rsc start --port="${port}"
```

**However, there's another `module purge` at the very beginning of `job_script_content.sh`**:

```sh
$ cd ~/ondemand
$ grep -n -F purge -r --include="*"
data/sys/dashboard/batch_connect/sys/RStudio/output/36042511-00e3-4730-9c47-e672abb30be7/job_script_content.sh:2:module purge
```

which I think prevents users from loading module in their ~/.bashrc.

That script is not in this repo, but here's a summary:

```sh
$ cat ~/ondemand/data/sys/dashboard/batch_connect/sys/RStudio/output/36042511-00e3-4730-9c47-e672abb30be7/job_script_content.sh

module purge
cd /c4/home/henrik/ondemand/data/sys/dashboard/batch_connect/sys/RStudio/output/36042511-00e3-4730-9c47-e672abb30be7

# Export useful connection variables
export host
export port

...

# Wait for script process to finish
wait ${SCRIPT_PID} || clean_up 1

# Exit cleanly
clean_up
```

**Comment by hgputnam** [comment]
Ugh, that might be a problem. I hate to start modifying the core code. What about trying to put something like `source ~/.bashrc` in the after.sh.erb file or the script.sh.erb file?

**Comment by HenrikBengtsson** [comment]
I searched the Open OnDemand [source code](https://github.com/OSC/ondemand/) for `module purge` but couldn't find anything.  Then looked at the docs and found <https://osc.github.io/ood-documentation/latest/app-development/interactive/setup/modify-cluster-configuration.html?highlight=bashrc>, which led me to:

```yml
$ cat /etc/ood/config/clusters.d/c4.yml 
v2:
  metadata:
    title: "c4"
  login:
    host: "c4-log1"
  job:
    adapter: "slurm"
    cluster: "c4"
    bin: "/usr/bin"
    conf: "/etc/slurm/slurm.conf"
    bin_overrides:
      scancel: "/opt/slurm/scancel.sh"
  batch_connect:
    basic:
      script_wrapper: |
        module purge
        %s
      set_host: "host=$(hostname -A | awk '{print $1}')"
    vnc:
      script_wrapper: |
        module purge
        export PATH="/opt/TurboVNC/bin:$PATH"
        export WEBSOCKIFY_CMD="/usr/local/bin/websockify"
        %s
      set_host: "host=$(hostname -A | awk '{print $1}')"
```

Could that:

```yml
    basic:
      script_wrapper: |
        module purge
        %s
      set_host: "host=$(hostname -A | awk '{print $1}')"
```

be it?
